"""add additional charges payment concept

Revision ID: 22478cb46be3
Revises: 01d3a9cc0149
Create Date: 2026-07-31 14:58:00.967457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22478cb46be3'
down_revision: Union[str, Sequence[str], None] = '01d3a9cc0149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('concept',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('DEPOSIT', 'FINAL_PAYMENT', 'ADDITIONAL_CHARGES', 'EXTRA_HOURS', 'DAMAGES', name='payment_concept', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('concept',
               existing_type=sa.Enum('DEPOSIT', 'FINAL_PAYMENT', 'ADDITIONAL_CHARGES', 'EXTRA_HOURS', 'DAMAGES', name='payment_concept', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
