"""add payment receipt fields

Revision ID: aadf3ab61038
Revises: b0da981dce11
Create Date: 2026-07-26 16:13:04.967906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadf3ab61038'
down_revision: Union[str, Sequence[str], None] = 'b0da981dce11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_original_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_content_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('receipt_content_type')
        batch_op.drop_column('receipt_original_name')
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###
